"""Hardening tests — error paths, bad input, edge cases.

These cover the new defensive code added to cli.py and core.py: missing
files, unreadable paths, malformed YAML, empty intents, and I/O errors
on the output side.  No network, no Frida required.
"""
from __future__ import annotations

import json
import os
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from hookcraft.cli import main  # noqa: E402
from hookcraft.core import (  # noqa: E402
    HookcraftError,
    generate_script,
    lint_intent,
    parse_intent,
    parse_yaml,
)


# ---------------------------------------------------------------------------
# core: parse_yaml edge cases
# ---------------------------------------------------------------------------


def test_parse_yaml_empty_string_returns_none():
    """Empty / all-comment YAML must return None, not raise."""
    assert parse_yaml("") is None
    assert parse_yaml("# only a comment\n") is None


def test_parse_yaml_tab_indentation_raises():
    with pytest.raises(HookcraftError, match="tabs are not allowed"):
        parse_yaml("target: x\n\thooks: []\n")


def test_parse_yaml_malformed_mapping_raises():
    """A non-mapping top-level scalar line without ':' must raise."""
    with pytest.raises(HookcraftError):
        parse_yaml("target: x\nplatform: linux\njust_a_bare_word\n")


# ---------------------------------------------------------------------------
# core: parse_intent edge cases
# ---------------------------------------------------------------------------


def test_parse_intent_non_dict_raises():
    with pytest.raises(HookcraftError, match="root must be a mapping"):
        parse_intent(["not", "a", "dict"])


def test_parse_intent_missing_target_raises():
    with pytest.raises(HookcraftError, match="target"):
        parse_intent({"platform": "linux", "hooks": []})


def test_parse_intent_empty_target_raises():
    with pytest.raises(HookcraftError, match="target"):
        parse_intent({"target": "   ", "platform": "linux", "hooks": []})


def test_parse_intent_hooks_not_list_raises():
    with pytest.raises(HookcraftError, match="'hooks' must be a list"):
        parse_intent({"target": "app", "hooks": "not_a_list"})


def test_parse_intent_hook_not_dict_raises():
    with pytest.raises(HookcraftError, match=r"hooks\[0\]"):
        parse_intent({"target": "app", "hooks": ["just_a_string"]})


def test_parse_intent_empty_hooks_list_ok():
    """An empty hooks list is valid to parse; lint will flag it."""
    intent = parse_intent({"target": "myapp", "platform": "linux", "hooks": []})
    assert intent.target == "myapp"
    assert intent.hooks == []


# ---------------------------------------------------------------------------
# core: lint_intent edge cases
# ---------------------------------------------------------------------------


def test_lint_no_hooks_is_error():
    intent = parse_intent({"target": "x", "platform": "linux", "hooks": []})
    findings = lint_intent(intent)
    assert any(f.severity == "error" and "no hooks" in f.message for f in findings)


def test_lint_unknown_platform_is_warning():
    data = parse_yaml(
        "target: x\nplatform: commodore64\nhooks:\n"
        "  - name: h\n    kind: native_export\n    symbol: foo\n"
    )
    intent = parse_intent(data)
    findings = lint_intent(intent)
    assert any(f.severity == "warning" and "platform" in f.where for f in findings)


def test_lint_duplicate_hook_name_warns():
    data = parse_yaml(
        "target: x\nplatform: linux\nhooks:\n"
        "  - name: h\n    kind: native_export\n    symbol: foo\n"
        "  - name: h\n    kind: native_export\n    symbol: bar\n"
    )
    intent = parse_intent(data)
    findings = lint_intent(intent)
    assert any(f.severity == "warning" and "duplicate" in f.message for f in findings)


# ---------------------------------------------------------------------------
# core: generate_script edge cases
# ---------------------------------------------------------------------------


def test_generate_script_empty_hooks_produces_valid_js():
    """generate_script with zero hooks must not raise and must include the
    installed marker (count 0)."""
    intent = parse_intent({"target": "app", "platform": "linux", "hooks": []})
    script = generate_script(intent)
    assert "Generated by HOOKCRAFT" in script
    assert "_hookcraft: 'installed', count: 0" in script


def test_generate_unknown_kind_raises():
    intent = parse_intent({"target": "app", "platform": "linux", "hooks": []})
    from hookcraft.core import Hook
    intent.hooks.append(Hook(name="x", kind="bad_kind"))
    with pytest.raises(HookcraftError, match="unknown hook kind"):
        generate_script(intent)


# ---------------------------------------------------------------------------
# cli: missing / bad input file -> exit 2, clean stderr
# ---------------------------------------------------------------------------


def test_cli_missing_file_exits_2(capsys):
    rc = main(["generate", "/no/such/file/intent.yaml"])
    assert rc == 2
    err = capsys.readouterr().err
    assert "error" in err.lower()


def test_cli_missing_file_json_format(capsys):
    rc = main(["--format", "json", "generate", "/no/such/file.yaml"])
    assert rc == 2
    payload = json.loads(capsys.readouterr().out)
    assert payload["ok"] is False
    assert "error" in payload


def test_cli_directory_as_input_exits_2(tmp_path, capsys):
    """Passing a directory path instead of a file must exit 2 cleanly."""
    rc = main(["generate", str(tmp_path)])
    assert rc == 2
    err = capsys.readouterr().err
    assert "error" in err.lower()


def test_cli_malformed_yaml_exits_2(tmp_path, capsys):
    p = tmp_path / "bad.yaml"
    p.write_text("target: x\nplatform\thooks: []\n", encoding="utf-8")
    rc = main(["generate", str(p)])
    assert rc == 2
    err = capsys.readouterr().err
    assert "error" in err.lower()


def test_cli_empty_yaml_exits_2(tmp_path, capsys):
    """An empty YAML file (parses to None) must exit 2 with a clear message."""
    p = tmp_path / "empty.yaml"
    p.write_text("# nothing here\n", encoding="utf-8")
    rc = main(["generate", str(p)])
    assert rc == 2
    err = capsys.readouterr().err
    assert "error" in err.lower()


def test_cli_lint_missing_file_exits_2(capsys):
    rc = main(["lint", "/no/such/file.yaml"])
    assert rc == 2
    err = capsys.readouterr().err
    assert "error" in err.lower()


# ---------------------------------------------------------------------------
# cli: bad output path -> exit 2, clean stderr
# ---------------------------------------------------------------------------


def test_cli_generate_output_to_directory_exits_2(tmp_path, capsys):
    """Writing the script to a directory path (not a file) must exit 2."""
    demo = os.path.join(ROOT, "demos", "01-basic", "intent.yaml")
    rc = main(["generate", demo, "-o", str(tmp_path)])
    assert rc == 2
    err = capsys.readouterr().err
    assert "error" in err.lower()


# ---------------------------------------------------------------------------
# cli: no subcommand -> help, exit 0
# ---------------------------------------------------------------------------


def test_cli_no_subcommand_returns_0(capsys):
    rc = main([])
    assert rc == 0
    out = capsys.readouterr().out
    assert "hookcraft" in out
