"""Smoke tests for HOOKCRAFT.

These import the real engine, run it on the bundled demo intent, and assert
real behavior (no network, no Frida required).
"""

import json
import os
import sys

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from hookcraft import (  # noqa: E402
    TOOL_NAME,
    TOOL_VERSION,
    HookcraftError,
    build,
    generate_script,
    lint_intent,
    parse_intent,
    parse_yaml,
)
from hookcraft.cli import main  # noqa: E402

DEMO = os.path.join(ROOT, "demos", "01-basic", "intent.yaml")


def _demo_text():
    with open(DEMO, "r", encoding="utf-8") as fh:
        return fh.read()


def test_metadata():
    assert TOOL_NAME == "hookcraft"
    assert TOOL_VERSION.count(".") == 2


def test_yaml_subset_parses_scalars_and_lists():
    data = parse_yaml(
        "target: com.x\n"
        "platform: android\n"
        "count: 3\n"
        "enabled: true\n"
        "tags: [a, b, c]\n"
        "hooks:\n"
        "  - name: h1\n"
        "    kind: native_export\n"
        "    symbol: open\n"
    )
    assert data["target"] == "com.x"
    assert data["count"] == 3
    assert data["enabled"] is True
    assert data["tags"] == ["a", "b", "c"]
    assert isinstance(data["hooks"], list)
    assert data["hooks"][0]["symbol"] == "open"


def test_comments_and_tabs():
    data = parse_yaml("target: x  # inline comment\nplatform: linux\n")
    assert data["target"] == "x"
    with pytest.raises(HookcraftError):
        parse_yaml("target: x\n\thooks: []\n")


def test_parse_demo_intent():
    intent = parse_intent(parse_yaml(_demo_text()))
    assert intent.target == "com.example.bank"
    assert intent.platform == "android"
    assert len(intent.hooks) == 4
    names = {h.name for h in intent.hooks}
    assert {"build_auth_token", "ssl_verify", "strstr_probe", "native_plugin_loaded"} == names


def test_kind_inference():
    intent = parse_intent(parse_yaml(_demo_text()))
    probe = next(h for h in intent.hooks if h.name == "strstr_probe")
    assert probe.kind == "native_export"  # inferred from `symbol`
    assert probe.symbol == "strstr"


def test_demo_lints_clean_of_errors_with_info():
    intent = parse_intent(parse_yaml(_demo_text()))
    findings = lint_intent(intent)
    assert not any(f.severity == "error" for f in findings)
    # strstr_probe has no module -> info finding
    assert any(f.severity == "info" and "module" in f.message for f in findings)


def test_generate_produces_real_frida_js():
    intent = parse_intent(parse_yaml(_demo_text()))
    script = generate_script(intent)
    assert "Generated by HOOKCRAFT" in script
    # one block per hook kind present
    assert "Interceptor.attach" in script
    assert "Java.perform" in script
    assert "Module.findExportByName" in script
    assert "MODULE_OBSERVERS.push" in script
    # overload rendered
    assert '.overload("java.lang.String", "int")' in script
    # final marker counts all 4 hooks
    assert "_hookcraft: 'installed', count: 4" in script
    # backtrace requested only on build_auth_token
    assert "getStackTraceString" in script


def test_build_strict_raises_on_missing_required_field():
    bad = (
        "target: com.x\n"
        "platform: android\n"
        "hooks:\n"
        "  - name: broken\n"
        "    kind: native_export\n"  # no symbol
    )
    with pytest.raises(HookcraftError):
        build(bad, strict=True)
    # non-strict still produces something but reports the error
    script, intent, findings = build(bad, strict=False)
    assert any(f.severity == "error" for f in findings)
    assert "Interceptor.attach" in script


def test_address_hook_validation():
    bad = (
        "target: p\nplatform: linux\n"
        "hooks:\n  - name: a\n    kind: address\n    address: nothex\n"
    )
    intent = parse_intent(parse_yaml(bad))
    findings = lint_intent(intent)
    assert any(f.severity == "error" and "hex" in f.message for f in findings)


def test_cli_generate_table(capsys):
    rc = main(["generate", DEMO])
    out = capsys.readouterr().out
    assert rc == 0
    assert "Generated by HOOKCRAFT" in out


def test_cli_generate_json_format_before_and_after(capsys):
    # --format before the subcommand
    rc = main(["--format", "json", "generate", DEMO])
    payload = json.loads(capsys.readouterr().out)
    assert rc == 0
    assert payload["ok"] is True
    assert payload["hooks"] == 4
    assert payload["target"] == "com.example.bank"
    assert "send(" in payload["script"]
    assert isinstance(payload["findings"], list)

    # --format after the subcommand must also work
    rc2 = main(["generate", DEMO, "--format", "json"])
    payload2 = json.loads(capsys.readouterr().out)
    assert rc2 == 0
    assert payload2["hooks"] == 4


def test_cli_lint_nonzero_on_error(tmp_path, capsys):
    p = tmp_path / "bad.yaml"
    p.write_text(
        "target: p\nplatform: ios\nhooks:\n  - name: x\n    kind: objc_method\n",
        encoding="utf-8",
    )
    rc = main(["lint", str(p)])
    assert rc == 1  # missing selector -> error -> CI gate fails


def test_cli_version(capsys):
    with pytest.raises(SystemExit) as exc:
        main(["--version"])
    assert exc.value.code == 0
    out = capsys.readouterr().out
    assert "hookcraft" in out
